---
title: "Valência nas proposições"
output:
  html_document:
    theme: paper
    css: styles.css
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  # fig.cap = '',
  warning = FALSE,
  # fig.align = 'center',
  fig.width = 8,
  fig.height = 5
)

Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggbeeswarm)
library(ggchicklet)
library(hrbrthemes)
library(reactable)
theme_set(theme_ipsum_rc())

source(here::here("code/read_ready.R"))
source(here::here("reports/autorias.R"))
```

```{r}
proposicoes = read_proposicoes()
detalhes_autorias = read_autorias_det()
resumo_autorias = read_autorias_res() %>%  select(-situacao,
                                                  -em_exercicio,
                                                  -is_parlamentar,
                                                  -sexo,
                                                  -starts_with("id"))
```

```{r}
proposicoes %>% 
  count(casa_origem, classificacao_ambientalismo) %>% 
  ggplot(aes(x = classificacao_ambientalismo, y = n)) + 
  facet_grid(. ~ casa_origem) + 
  geom_chicklet() +
  coord_flip()
  
```

```{r}
proposicoes %>% 
  count(sigla_tipo, classificacao_ambientalismo) %>% 
  group_by(sigla_tipo) %>% 
  mutate(n_tipo = sum(n)) %>% 
  ungroup() %>% 
  mutate(sigla_tipo = str_glue("{sigla_tipo} ({n_tipo})")) %>% 
  ggplot(aes(x = reorder(sigla_tipo, n, sum), y = n, fill = classificacao_ambientalismo)) + 
  geom_col(position = "fill") + 
  scale_y_percent() + 
  coord_flip()
```

```{r}
proposicoes %>% 
  filter(lubridate::year(data_apresentacao) >= 2019) %>% 
  mutate(mes = lubridate::floor_date(data_apresentacao, "months")) %>% 
  count(mes, classificacao_ambientalismo) %>% 
  ggplot(aes(x = mes, y = n, fill = classificacao_ambientalismo)) + 
  geom_col() + 
  facet_grid(classificacao_ambientalismo~ . )
```

