---
title: "Proposições segundo a convergência com agenda ambientalista"
output:
  html_document:
    theme: paper
    css: styles.css
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  # fig.cap = '',
  warning = FALSE,
  # fig.align = 'center',
  fig.width = 8,
  fig.height = 5
)

Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggbeeswarm)
library(ggchicklet)
library(hrbrthemes)
library(reactable)
theme_set(theme_ipsum_rc())

source(here::here("code/read_ready.R"))
source(here::here("reports/autorias.R"))
source(here::here("reports/escalas.R"))
```

As proposições foram rotuladas como tendo efeito convergente, divergente ou sem clara definição para a pauta da defesa do meio ambiente e clima. 

```{r}
proposicoes = read_proposicoes() 
detalhes_autorias = read_autorias_det()
resumo_autorias = read_autorias_res() %>%  select(-sexo,
                                                  -starts_with("id"))
```


```{r fig.height=4}
proposicoes %>%
  filter(!is.na(efeito)) %>% 
  count(efeito) %>%
  ggplot(aes(x = efeito, y = n, fill = efeito)) +
  geom_chicklet() +
  escala_sinais +
  coord_flip() +
  labs(
    title = "Convergência das Proposições no geral",
    subtitle = "Todos os tipos e em ambas as casas",
    x = "",
    y = "Proposições"
  ) + theme(legend.position = 'none')
```


```{r fig.height=4}
proposicoes %>% 
  filter(!is.na(casa_origem)) %>% 
  count(casa_origem, efeito) %>% 
  ggplot(aes(x = efeito, y = n, fill = efeito)) + 
  facet_grid(. ~ casa_origem) + 
  geom_chicklet() +
  coord_flip() + 
  escala_sinais +
  theme(legend.position = 'none') + 
  labs(
    title = "Convergência das Proposições por casa de origem",
    subtitle = "Todos os tipos",
    x = "",
    y = "Proposições"
  ) + theme(legend.position = 'none')
```

```{r}
proposicoes %>% 
  filter(!is.na(casa_origem)) %>% 
  separate_rows(tema, sep = ";") %>%
  mutate(tema = case_when(
    tema == "Meio ambiente" ~ "Meio Ambiente e Desenvolvimento Sustentável", 
    tema == "Agricultura, pecuária e abastecimento" ~ "Agricultura, Pecuária, Pesca e Extrativismo", 
    TRUE ~ tema 
  )) %>% 
  count(tema, casa_origem, efeito) %>% 
  ggplot(aes(x = reorder(tema, n), y = n, fill = efeito)) + 
  facet_grid(. ~ casa_origem) + 
  geom_chicklet(position = "fill") +
  coord_flip() + 
  scale_y_percent() +
  escala_sinais +
  theme(legend.position = 'none') + 
  labs(
    title = "Convergência das Proposições",
    subtitle = "Proporcional por tema",
    x = "",
    y = "Proposições"
  ) + theme(legend.position = 'none')
```


```{r}
proposicoes %>% 
  filter(!is.na(efeito)) %>% 
  count(sigla_tipo, efeito) %>% 
  group_by(sigla_tipo) %>% 
  mutate(n_tipo = sum(n)) %>% 
  ungroup() %>% 
  mutate(sigla_tipo = str_glue("{sigla_tipo} ({n_tipo})")) %>% 
  ggplot(aes(x = reorder(sigla_tipo, n, sum), y = n, fill = efeito)) + 
  geom_col(position = "fill") + 
  escala_sinais +
  scale_y_percent() + 
  coord_flip() + 
  labs(
    title = "Convergência das Proposições por tipo",
    subtitle = "Número entre parêntese mostra quantas temos classificadas do tipo",
    x = "",
    y = "% das Proposições"
  ) + theme(legend.position = 'none')
```

```{r}
proposicoes %>% 
  filter(!is.na(efeito)) %>% 
  filter(lubridate::year(data_apresentacao) >= 2019) %>% 
  mutate(mes = lubridate::floor_date(data_apresentacao, "months")) %>% 
  count(mes, efeito) %>% 
  ggplot(aes(x = mes, y = n, fill = efeito)) + 
  geom_col(color = "black") + 
  escala_sinais + 
  facet_grid(efeito~ ., scales = "free") + 
  labs(
    title = "Proposições e sinal ao longo do tempo",
    subtitle = "Todos os tipos e em ambas as casas",
    x = "",
    y = "Proposições"
  ) + theme(legend.position = 'none')
```

## Números de autores

```{r}
participacao = detalhes_autorias %>%
  filter(!is.na(efeito), !(sigla_tipo %in% c("PEC", "MPV"))) %>% 
  group_by(proposicao, efeito) %>% 
  filter(!is.na(partido)) %>% 
  summarise(autores = n(), 
            partidos = n_distinct(partido), 
            .groups = "drop")

mais_autores = participacao %>% 
  filter(efeito != "Neutro") %>% 
  group_by(efeito) %>% 
  slice_max(autores, n = 10, with_ties = F) %>% 
  ungroup()

mais_partidos = participacao %>% 
  filter(efeito != "Neutro") %>% 
  group_by(efeito) %>% 
  slice_max(partidos, n = 10, with_ties = F) %>% 
  ungroup()
```

```{r}
participacao %>% 
  filter(autores > 1) %>% 
  ggplot(aes(x = efeito, y = autores, color = efeito)) + 
  geom_quasirandom(show.legend = F) + 
  escala_cor_sinais +
  coord_flip() + 
  labs(x = "", 
       title = "Proposições de cada efeito com mais de 1 autor"
       )
```


```{r}
mais_autores %>% 
  ggplot(aes(x = reorder(proposicao, autores), y = autores, fill = efeito)) + 
  geom_chicklet(width = .75) +
  facet_grid(reorder(efeito, -autores) ~ ., scales = "free") + 
  escala_sinais + 
  coord_flip() + 
  labs(x = "", 
       title = "Proposições de cada efeito com mais autores",
       subtitle = "10 proposições com efeito convergente/divergente com mais autores",
       fill = "Efeito") + 
  theme(legend.position = "None")
```

```{r}
mais_autores %>% 
  select(proposicao, autores) %>% 
  left_join(proposicoes %>% select(nome_proposicao, ementa), 
            by = c("proposicao" = "nome_proposicao")) %>% 
  arrange(-autores) %>% 
  reactable(searchable = T)
```

```{r}
participacao %>%
  filter(partidos > 1) %>%
  ggplot(
    aes(x = efeito, y = partidos, color = efeito)
  ) +
  geom_quasirandom(show.legend = F) +
  escala_cor_sinais +
  coord_flip() +
  scale_y_continuous(breaks = scales::pretty_breaks()) +
  labs(x = "",
       title = "Proposições de cada efeito com mais de 1 partido autor")
```


```{r}
mais_partidos %>%
  ggplot(aes(
    x = reorder(proposicao, partidos),
    y = partidos,
    fill = efeito
  )) +
  geom_chicklet(width = .75) +
  facet_grid(reorder(efeito,-autores) ~ ., scales = "free") +
  escala_sinais +
  coord_flip() +
  labs(
    x = "",
    title = "Proposições de cada efeito com mais partidos autores",
    subtitle = "10 proposições com efeito convergente/divergente com mais partidos",
    fill = "Efeito"
  ) +
  theme(legend.position = "None")
```

```{r}
mais_partidos %>% 
  select(proposicao, partidos) %>% 
  left_join(proposicoes %>% select(nome_proposicao, ementa), 
            by = c("proposicao" = "nome_proposicao")) %>% 
  arrange(-partidos) %>% 
  reactable(searchable = T)
```

