---
title: "Situação das proposições"
output:
  html_document:
    theme: paper
    css: styles.css
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  # fig.cap = '',
  warning = FALSE,
  # fig.align = 'center',
  fig.width = 8,
  fig.height = 5
)

Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggbeeswarm)
library(ggchicklet)
library(hrbrthemes)
library(reactable)
theme_set(theme_ipsum_rc())

source(here::here("code/read_ready.R"))
source(here::here("reports/autorias.R"))
source(here::here("reports/escalas.R"))
```

```{r}
proposicoes = read_proposicoes()
detalhes_autorias = read_autorias_det()
resumo_autorias = read_autorias_res() %>%  
  select(-sexo,
         -starts_with("id"))
```

## Avanço na tramitação

```{r}
situacao = proposicoes %>% 
  pivot_longer(c(urgencia, avanco, status), names_to = "aspecto", values_to = "situacao") 
```


```{r}
situacao %>%
  filter(
    !(sigla_tipo %in% c("PEC", "MPV")),
    !(situacao %in% c("Ativa", "Sem urgência", "Ainda no início")),
    !is.na(situacao)) %>%
  count(aspecto, situacao, classificacao_ambientalismo) %>%
  ggplot(aes(x = situacao, y = n, fill =  classificacao_ambientalismo)) +
  facet_grid(reorder(aspecto,-n) ~ ., scales = "free") +
  geom_chicklet() +
  escala_sinais +
  coord_flip() +
  labs(
    title = "Situação de avanço das proposições",
    subtitle = "Características de avanço do Parlametria. Ignora PECs e MPVs.",
    x = "",
    fill = "Efeito",
    y = "Proposições"
  )
```

Progresso das PECs apresentadas em 2019 e 2020:

```{r}
situacao %>%
  filter(sigla_tipo == "PEC",
         aspecto != "urgencia") %>%
  count(aspecto, situacao, classificacao_ambientalismo) %>%
  ggplot(aes(x = situacao, y = n, fill =  classificacao_ambientalismo)) +
  facet_grid(reorder(aspecto, -n) ~ ., scales = "free") +
  geom_chicklet() +
  escala_sinais +
  coord_flip() +
  labs(
    title = "Situação de avanço das PECs",
    subtitle = "PECs apresentadas em 2019-2020",
    x = "",
    fill = "Efeito",
    y = "Proposições"
  )
```

TO DO: As MPVs ativas abaixo não estão ativas. Falta corrigirmos isso. 

```{r}
situacao %>%
  filter(sigla_tipo == "MPV",
         aspecto == "status") %>% 
  count(aspecto, situacao, classificacao_ambientalismo) %>%
  ggplot(aes(x = situacao, y = n, fill =  classificacao_ambientalismo)) +
  facet_grid(reorder(aspecto, -n) ~ ., scales = "free") +
  geom_chicklet() +
  escala_sinais +
  coord_flip() +
  labs(
    title = "Situação de avanço das MPs",
    x = "",
    fill = "Efeito",
    y = "Proposições"
  )
```

### Proposições de efeito negativo que tiveram tramitação avançada

```{r}
situacao %>%
  filter(
    situacao %in% c(
      "Avançou em uma casa",
      "Aprovada",
      "Avançou em comissões",
      "Urgência aprovada", 
      "Urgência apresentada"
    ),!is.na(situacao),
    classificacao_ambientalismo == "Negativo"
  ) %>%
  arrange(situacao) %>% 
  select(Proposição = nome_proposicao, situacao, ementa) %>% 
  reactable(searchable = T, striped = T, compact = T)
```

### Proposições de efeito POSITIVO que tiveram tramitação avançada

```{r}
situacao %>%
  filter(
    situacao %in% c(
      "Avançou em uma casa",
      "Aprovada",
      "Avançou em comissões",
      "Urgência aprovada", 
      "Arquivada",
      "Urgência apresentada"
    ),!is.na(situacao),
    classificacao_ambientalismo == "Positivo"
  ) %>%
  arrange(situacao) %>% 
  select(Proposição = nome_proposicao, situacao, ementa) %>% 
  reactable(searchable = T, striped = T, compact = T)
```



```{r}
situacao %>%
  filter(
    !(sigla_tipo %in% c("PEC", "MPV")),
    !(situacao %in% c("Ativa", "Sem urgência", "Ainda no início")),
    !is.na(situacao)) %>%
  count(aspecto, situacao, sigla_tipo) %>%
  ggplot(aes(x = situacao, y = n, fill =  sigla_tipo)) +
  facet_grid(reorder(aspecto,-n) ~ ., scales = "free") +
  geom_chicklet() +
  coord_flip() +
  labs(
    title = "Situação de avanço das proposições",
    subtitle = "Características de avanço do Parlametria. Mostrando apenas proposições que avançaram.",
    x = "",
    fill = "Tipo",
    y = "Proposições"
  )
```

```{r}
prop_situacao = situacao %>% 
  filter(!is.na(situacao), !is.na(classificacao_ambientalismo), !(sigla_tipo %in% c("PEC", "MPV"))) %>% 
  group_by(aspecto, classificacao_ambientalismo) %>% 
  mutate(total_classe = n()) %>% 
  group_by(aspecto, situacao, classificacao_ambientalismo) %>% 
  filter(classificacao_ambientalismo != "Neutro") %>% 
  summarise(total = mean(total_classe), prop_situacao = n() / total, count_situacao = n())

prop_situacao %>% 
  filter(!(situacao %in% c("Ativa", "Sem urgência", "Ainda no início"))) %>% 
  ggplot(aes(x = situacao, y = prop_situacao, fill =  classificacao_ambientalismo)) + 
  facet_grid(reorder(aspecto, -prop_situacao) ~ ., scales = "free") + 
  geom_chicklet(position = "dodge") + 
  escala_sinais + 
  scale_y_percent() + 
  coord_flip() + 
  labs(
    title = "% das proposições em destaque", 
    subtitle = "De acordo com efeito esperado", 
    x = "", 
    y = "% das proposições com esse efeito", 
    fill = "Efeito esperado"
  )
```


### Proposições aprovadas

```{r}
aprovadas = proposicoes %>%
  filter(status == "Aprovada") %>%
  select(`Proposição` =nome_proposicao, 
         `Apresentada em` = data_apresentacao, 
         `Casa de origem` = casa_origem, 
         Ementa = ementa)

aprovadas %>% reactable(striped = T, compact = T, searchable = T)
```

Eis seus autores:

```{r}
detalhes_autorias %>% 
  filter(proposicao %in% aprovadas$`Proposição`) %>% 
  mutate(governismo = round(governismo, 1)) %>% 
  select(proposicao, proposicao, nome, partido, uf, casa, governismo) %>%
  reactable()
```

```{r}
detalhes_autorias %>%
  filter(proposicao %in% aprovadas$`Proposição`, 
         sigla_tipo != 'MPV', 
         nome != 'Poder Executivo') %>%
  ggplot(aes(y = governismo, x = reorder(proposicao, governismo), color = classificacao_ambientalismo)) +
  geom_quasirandom(size = 2) + 
  escala_cor_sinais + 
  coord_flip() + 
  labs(title = "Governismo dos autores de proposições aprovadas", 
       x = "", 
       subtitle = "Cada ponto é um autor",
       color = "Efeito")
```
