---
title: "Autorias nas proposições"
output:
  html_document:
    theme: paper
    css: styles.css
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # message = FALSE,
  # warning = FALSE,
  # fig.cap = '',
  # fig.align = 'center',
  fig.width = 8,
  fig.height = 8
)

Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(ggchicklet)
library(ggbeeswarm)
library(hrbrthemes)
theme_set(theme_ipsum_rc())

source(here::here("code/read_ready.R"))
source(here::here("reports/autorias.R"))
source(here::here("reports/escalas.R"))
```

```{r}
proposicoes = read_proposicoes()
parlamentares = read_parlamentares() %>% 
  filter(em_exercicio == 1) %>% 
  select(-em_exercicio)
detalhes_autorias = read_autorias_det()
resumo_autorias_todos = read_autorias_res() %>%
  select(-sexo,
         -starts_with("id"))
resumo_autorias = resumo_autorias_todos %>%
  filter(assinadas > 0)
resumo_autorias_todos = resumo_autorias_todos %>% 
  mutate(assinou = if_else(assinadas > 0, "Apresentou prop. de MA", "Não apresentou")) 
```


```{r}
resumo_autorias %>%
  select(-governismo_ma) %>% 
  tbl_autorias_resumida()
```

#### Detalhes

```{r}
detalhes_autorias %>% 
  select(-id_entidade, -sigla_tipo, -governismo_ma) %>% 
  tbl_detalhes_autorias()
```

Proposições de Célio Studart


```{r}
detalhes_autorias %>% 
  filter(nome == "Célio Studart") %>% 
  select(proposicao) %>% 
  left_join(proposicoes, by = c("proposicao" = "nome_proposicao")) %>% 
  select(proposicao, urgencia, avanco, efeito, ementa) %>% 
  reactable(defaultColDef = coluna_default, sortable = T, searchable = T)

```



### Perfil dos autores


```{r}
resumo_autorias_todos %>% 
  filter(!is.na(governismo)) %>%
  ggplot(aes(
    x = governismo,
    fill = assinou
  )) +
  geom_histogram(binwidth = 2, boundary = 0) + 
  scale_fill_brewer(palette = "Set2") +
  facet_grid(casa ~ ., scales = "free") + 
  labs(
    x = "Governismo (neg. sign. oposição)",
    y = "Parlamentares",
    title = "Governismo e autoria de propostas",
    size = "Apresentou/Não apresentou"
  )
```

```{r}
resumo_autorias_todos %>% 
  filter(!is.na(governismo)) %>%
  ggplot(aes(
    x = governismo,
    fill = assinou
  )) +
  geom_histogram(binwidth = 2, boundary = 0, position = "fill") + 
  scale_y_percent() + 
  scale_fill_brewer(palette = "Set2") +
  facet_grid(casa ~ ., scales = "free") + 
  labs(
    x = "Governismo (neg. sign. oposição)",
    y = "Parlamentares",
    title = "Governismo e autoria de propostas",
    size = "Apresentou/Não apresentou"
  )
```


```{r}
resumo_autorias_todos %>%
  filter(!is.na(governismo)) %>%
  ggplot(aes(
    y = governismo,
    x = reorder(assinou, -governismo),
    size = autorias_ponderadas,
    color = assinou
  )) +
  facet_grid(casa ~ .) +
  coord_flip() +
  scale_color_brewer(palette = "Set2") + 
  geom_quasirandom(alpha = .6, position = "dodge") +
  labs(
    y = "Governismo (neg. sign. oposição)",
    x = "",
    title = "Governismo e autoria de propostas",
    subtitle = "Cada ponto é um(a) parlamentar. Maiores autoraram mais.",
    size = "Autorias poderadas"
  ) +
  theme(legend.position = "None")
```

```{r}
resumo_autorias_todos %>% 
  filter(!is.na(peso_politico)) %>% 
  ggplot(aes(
    x = peso_politico,
    fill = assinou
  )) +
  geom_histogram(binwidth = .05, boundary = 0) + 
  scale_fill_brewer(palette = "Set2") +
  facet_grid(casa ~ ., scales = "free") + 
  labs(
    x = "Governismo (neg. sign. oposição)",
    y = "Parlamentares",
    title = "Peso político e autoria de propostas",
    fill = "Apresentou/Não apresentou"
  )
  
```
```{r}
resumo_autorias_todos %>% 
  filter(!is.na(peso_politico + governismo)) %>% 
  ggplot(aes(y = peso_politico, x = governismo, color = assinou)) + 
  facet_grid(casa ~ .) + 
  geom_point(alpha = .4) + 
  scale_color_manual(values = c("brown", "blue")) + 
  labs(y = "Peso político no parlametria", 
       x = "Governismo", 
       title = "Peso político entre autores das PDLs", 
       subtitle = "Cada ponto é um(a) parlamentar. Maiores autoraram mais.",
       color = "Apresentou proposta em MA?") 
```


## Autoria dos partidos

```{r}
autorias_partidos = 
  detalhes_autorias %>% 
  select(proposicao, partido, efeito) %>% 
  distinct()
```


```{r}
autorias_efeito = autorias_partidos %>%
  filter(!is.na(partido)) %>% 
  count(partido, efeito) %>%
  group_by(partido) %>% 
  mutate(total = sum(n)) %>% 
  ungroup() 

autorias_efeito %>% 
  ggplot(aes(x = reorder(partido, total), y = n, fill = efeito)) +
  geom_chicklet() +
  escala_sinais + 
  coord_flip() +
  labs(title = "Participação dos partidos na autoria das proposições",
       subtitle = "Pelo menos um(a) parlamentar do partido é autor(a)",
       x = "", y = "Proposições autoradas por parlamentar do partido", 
       fill = "Convergência")
```

```{r}
bancadas = parlamentares %>% 
  count(partido, name = "bancada")

autorias_media = autorias_efeito %>% 
  left_join(bancadas, by = "partido") %>% 
  mutate(n = n/bancada, total = total / bancada) 

autorias_media %>% 
  ggplot(aes(x = reorder(partido, total), y = n, fill = efeito)) +
  geom_chicklet() +
  escala_sinais + 
  coord_flip() +
  labs(title = "Participação ponderada dos partidos na autoria das proposições",
       subtitle = "Número médio de proposições assinadas por parlamentar.",
       x = "", y = "Proposições por parlamentar do partido (média)", 
       fill = "Convergência")
```

Sem o PV, para facilitar a comparação dos demais.

```{r}
autorias_media %>% 
  filter(partido != "PV") %>% 
  ggplot(aes(x = reorder(partido, total), y = n, fill = efeito)) +
  geom_chicklet() +
  escala_sinais + 
  coord_flip() +
  labs(title = "Número médio de proposições por parlamentar",
       subtitle = "Exceto PV. Número médio de proposições assinadas por parlamentar.",
       x = "", y = "Proposições por parlamentar do partido (média)", 
       fill = "Convergência")
```


```{r fig.height=8}
autorias_partidos %>%
  filter(!is.na(partido)) %>% 
  count(partido, efeito) %>%
  mutate(efeito = factor(efeito, levels = c("Convergente", "Neutro", "Divergente"), ordered = T)) %>% 
  group_by(partido) %>% 
  mutate(total = sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(partido, total), y = n, fill = efeito)) +
  geom_col(position = "fill") +
  scale_y_percent() + 
  escala_sinais + 
  coord_flip() +
  labs(title = "Participação dos partidos na autoria das proposições",
       subtitle = "Pelo menos um(a) parlamentar do partido é autor(a)",
       x = "", y = "PDLs autordas por parlamentar do partido", 
       fill = "Convergência")
```


```{r}
autorias_partidos %>%
  filter(!is.na(partido)) %>% 
  count(partido, efeito, sort = T, name = "Proposições") %>%
  select(Partido = partido, Efeito = efeito, `Proposições`) %>% 
  reactable(searchable = T)
```

