---
title: "Governismo e apoio ao MA"
output:
  html_document:
    theme: paper
    css: styles.css
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # message = FALSE,
  # warning = FALSE,
  # fig.cap = '',
  # fig.align = 'center',
  fig.width = 6,
  fig.height = 5
)

Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(ggchicklet)
library(ggbeeswarm)
library(hrbrthemes)
library(reactable)
theme_set(theme_ipsum_rc())

source(here::here("code/read_ready.R"))
source(here::here("reports/escalas.R"))

coluna_default = colDef(
  header = function(value)
    gsub("_", " ", value, fixed = TRUE) %>% str_to_sentence(),
  cell = function(value)
    format(value, nsmall = 1, digits = 2),
  na = "-"
)
```

[Planilha com detalhes de todos os votos](https://docs.google.com/spreadsheets/d/1vwSEPmk9AXFtkkBGajgREhIWKNfg0OosccQwk-7tiGM/edit#gid=0).

```{r}
votacoes_todas = read_votacoes() %>% 
  mutate(
    texto_obj = if_else(is.na(obj_votacao), "?", paste0(str_sub(obj_votacao, 1, 25), "...")),
    objeto = str_glue("{nome_proposicao} - {id_votacao} ({texto_obj})"), 
    orientacao_planilha = if_else(is.na(orientacao_ma), "Sem orientação", orientacao_ma)) 

proposicoes = read_proposicoes() %>% 
  select(nome_proposicao, efeito = classificacao_ambientalismo)

votacoes = votacoes_todas %>% 
  filter(votos_capturados > 20) %>% 
  left_join(proposicoes, by = c("nome_proposicao"))  
```

## Visão geral das votações nominais

Houve um total de 2309 votações na Câmara e 185 no Senado no biênio. Dessas, analisamos `r NROW(votacoes_todas)` como sendo possivelmente de MA. Filtrando as que são nominais, eis as posições que temos: 


```{r}
votacoes %>% 
  count(casa, orientacao_planilha) %>% 
  reactable(
    striped = T, 
    compact = T, 
    defaultColDef = coluna_default
  )
```

```{r}
votacoes %>% 
  filter(!is.na(efeito)) %>% 
  count(efeito) %>% 
  ggplot(aes(x = reorder(efeito, -n), 
             y = n, 
             fill = efeito)) + 
  escala_sinais + 
  geom_col(show.legend = F) + 
  labs(
    title = "O que vai a votação nominal?", 
    subtitle = "Proposições com que tipo de efeito", 
    x = "", 
    y = "Votações"
  )
```


```{r fig.height=9}
votacoes %>% 
  ggplot(aes(x = reorder(nome_proposicao, consenso, min), y = consenso, 
             color = orientacao_planilha)) + 
  geom_point(alpha = .8, size = 3) + 
  facet_grid(reorder(efeito, -consenso) ~ ., scales = "free") + 
  scale_y_continuous(position = "right") +  
  coord_flip() + 
  labs(
    title = "Consenso nas votações nominais", 
    subtitle = "De acordo com efeito das proposições", 
    x = "", 
    y = "Consenso (índice de Rice)", 
    color = "Orientação"
  ) + 
  theme(legend.position = "top")
```

## Quanto apoio houve? 

```{r fig.height=8, fig.width=10}
votacoes_long = votacoes %>%
  filter(casa == "camara",
         orientacao_ma %in% c("Sim", "Não")) %>%
  pivot_longer(
    c(votos_favoraveis, votos_contra, votos_indef),
    names_to = "voto",
    values_to = "n"
  )

votacoes_long %>% 
  mutate(voto = str_replace(voto, "votos_", "") %>% factor(levels = c("favoraveis", "indef", "contra"), ordered = T)) %>% 
  ggplot(aes(x = reorder(objeto, data), y = n, fill = voto)) + 
  geom_chicklet() + 
  scale_fill_manual(values = c("favoraveis" = "#91cf60",
    "contra" = "#fc8d59",
    "indef" = "#ffff8a")) +
  scale_y_continuous(position = "right") +  
  coord_flip() + 
  labs(
    title = "Resultado de votações nominais", 
    subtitle = "Votações com resultado publicado e orientação de MA", 
    x = "",
    y = "Votos",
    fill = "Em relação ao MA"
  )
  
```

### Quando tivemos mais de um quarto dos votos? 

```{r}
votacoes %>% 
  filter(votos_favoraveis / votos_sim_nao > .25) %>% 
  select(nome_proposicao, orientacao_ma, ementa_proposicao, obj_votacao, resumo, data, apoio, efeito) %>% 
  reactable(
    striped = T, 
    compact = T, 
    defaultColDef = coluna_default
  )  
```

